name: terraform
on:
  push:
    branches: [ "main" ]
    paths: [ "infra/**", ".github/workflows/terraform.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "infra/**", ".github/workflows/terraform.yml" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Terraform Plan
        run: terraform -chdir=infra plan -input=false -out=tfplan

      - name: Terraform Apply (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=infra apply -input=false -auto-approve tfplan
